application: tasks
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/

- url: .*
  script: tasks.py
